# -*- coding: utf-8 -*-
"""Testing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1otQXebUROzMjUsehoDX7ETYwHHvBiFtK
"""

from google.colab import files
uploaded = files.upload()  # Upload Excel-mu (misal awareness.xlsx)

import pandas as pd
import re
import os
from google.colab import files

# GANTI nama file sesuai yang kamu upload
EXCEL_FILE = "dataTest.xlsx"  # Contoh: "dataTest.xlsx" atau nama aslinya

# Baca Excel
df = pd.read_excel(EXCEL_FILE)

# Preview data biar yakin
print("Data berhasil dibaca! Total baris:", len(df))
print(df[['judul', 'subjudul', 'tahun', 'organisasi']].head())

def generate_awareness_html(row):
    judul = str(row['judul']).upper() if pd.notna(row['judul']) else "AWARENESS"
    subjudul = str(row['subjudul']) if pd.notna(row['subjudul']) else ""
    tahun = str(row['tahun']) if pd.notna(row['tahun']) else "2025"
    organisasi = str(row['organisasi']) if pd.notna(row['organisasi']) else "Team"

    # Gabung konten jadi card (maks 6)
    cards = []
    konten_cols = [col for col in df.columns if 'konten' in col.lower() or 'subkonten' in col.lower()]
    for i, col in enumerate(konten_cols[:6]):
        if pd.notna(row[col]):
            content = str(row[col])
            cards.append(f"""
            <td width="33%" valign="top" style="padding:15px;">
              <table width="100%" bgcolor="#FFFFFF" cellpadding="20" cellspacing="0" style="border-radius:15px; box-shadow:0 4px 15px rgba(0,0,0,0.1);">
                <tr><td align="center">
                  <img src="https://img.freepik.com/free-vector/compliance-concept-illustration_114360-472.jpg" width="120" style="border-radius:10px;">
                </td></tr>
                <tr><td style="font-size:16px; color:#333; text-align:left;">
                  {content}
                </td></tr>
              </table>
            </td>
            """)

    cards_html = "<tr>" + "".join(cards) + "</tr>" if cards else "<tr><td style='font-size:18px; color:#777;'>Konten belum tersedia</td></tr>"

    html = f"""
<table width="100%" bgcolor="#F5F7FA" cellpadding="0" cellspacing="0">
  <tr><td align="center" style="padding:40px;">
    <table width="700" bgcolor="#FFFFFF" style="max-width:700px; border-radius:20px; box-shadow:0 10px 30px rgba(0,0,0,0.1);">
      <tr>
        <td align="center" bgcolor="#0055A4" style="padding:50px; color:#FFF; border-radius:20px 20px 0 0;">
          <img src="https://img.freepik.com/free-vector/cyber-security-concept-illustration_114360-385.jpg" width="250" style="border-radius:15px;">
          <br><br>
          <div style="font-size:50px; font-weight:bold;">AWARENESS</div>
          <div style="font-size:36px; color:#F28C38;">{judul}</div>
        </td>
      </tr>
      <tr>
        <td align="center" style="padding:30px; font-size:24px; color:#333;">
          {subjudul} • {tahun} - {organisasi}
        </td>
      </tr>
      <tr>
        <td style="padding:0 40px 40px;">
          <table width="100%">{cards_html}</table>
        </td>
      </tr>
      <tr>
        <td align="center" bgcolor="#0055A4" style="padding:40px; color:#FFF; border-radius:0 0 20px 20px;">
          <a href="https://yourcompany.sharepoint.com/awareness" style="background:#F28C38; color:#FFF; padding:15px 40px; text-decoration:none; border-radius:30px; font-weight:bold; font-size:18px;">
            Baca Detail di SharePoint
          </a>
        </td>
      </tr>
    </table>
  </td></tr>
</table>
    """
    return html

os.makedirs("html_output", exist_ok=True)
generated_files = []

for i, row in df.iterrows():
    if pd.notna(row['judul']):
        html = generate_awareness_html(row)
        safe_name = re.sub(r'[^\w\-_.]', '_', str(row['judul']))[:50]
        filename = f"html_output/awareness_{i+1}_{safe_name}.html"
        with open(filename, "w", encoding="utf-8") as f:
            f.write(html)
        generated_files.append(filename)
        print(f"✓ {filename}")

print(f"\nSELESAI! {len(generated_files)} file HTML dibuat")

import shutil
shutil.make_archive("awareness_html", 'zip', "html_output")
files.download("awareness_html.zip")

from google.colab import files
import shutil

# Ganti "nama_folder" kalau ada folder spesifik, atau skip buat semua
shutil.make_archive("colab_all_files", 'zip', "/content")  # Zip semua di /content

files.download("colab_all_files.zip")